### ISSUE TITLE
[Codebundle] Networkpolicy triage

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/rw-cli-codecollection#12]
Report or make recommendations on networkpolicy configurations; 

- [ ] core tasks created
- [ ] tag/docstring created
- [ ] command-list additions/flags
- [ ] raiseissue added

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
