### ISSUE TITLE
[Codebundle] Istio Triage

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/rw-cli-codecollection#13]
Triage a popular service mesh implementation (likely istio): 
- [ ] lab resources deployed
- [ ] core tasks created
- [ ] tag/docstring created
- [ ] command-list additions/flags
- [ ] raiseissue added

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
