### ISSUE TITLE
[Codebundle] Ansible tower integration

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/rw-cli-codecollection#148]
**Scope**
Connects TaskSets into Ansible Tower

**Requested By (Optional)**
- N/A

**Related Integrations**
eg:
- Kubernetes
- Prometheus

**Definition of Done**
- [ ] Codebundle Implementation accomplishes scope (or provide a justification for why it may differ)
- [ ] Attach a screenshot of the codebundle pushing a metric locally (if an SLI) or showing a report (if a taskset)
- [ ] Attach a screenshot of the SLI or Taskset running in a workspace.

**Optional Comments**

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
