### ISSUE TITLE
[Codebundle] Postgresql Slowquery Inspection Report

### ISSUE THREAD

**Issue by jon-funk** [runwhen-contrib/rw-cli-codecollection#159]
**Scope**
Runs a taskset which fetches a list of slowqueries in a postgresql database. The user should be able to configure what constitutes as a slowquery (eg: is beyond X memory / elapsed time)

**Requested By (Optional)**
- RunWhen

**Related Integrations**
- Kubernetes
- Postgresql

**Definition of Done**
- [x] Codebundle Implementation accomplishes scope (or provide a justification for why it may differ)
- [x] Attach a screenshot of the codebundle pushing a metric locally (if an SLI) or showing a report (if a taskset)
- [x] Attach a screenshot of the SLI or Taskset running in a workspace.

**Optional Comments**
This could potentially be split into 2 variants: one for public but authenticated db instances, and one for kubernetes workloads connected to via the kube api

**Comment by harsh098** [comment]
I would like to work on this issue @jon-funk .

**Comment by harsh098** [comment]
## Codebundle Repo
[https://github.com/harsh098/postgres-codecollection](https://github.com/harsh098/postgres-codecollection)

## Screenshots
**Taskset** :- Fetches list of long running queries on Postgres Clusters  
  

![image](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/23445112/8945bf86-2dee-4a6a-a58c-740303079b29)  

**SLI** :- Queries executing more than ${TIME_INTERVAL} milliseconds    
  

![image](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/23445112/01955907-b53c-4dda-92f0-e1219c29742e)

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
