### ISSUE TITLE
[Codebundle] Health check for Jenkins X

### ISSUE THREAD

**Issue by more-dinner** [runwhen-contrib/rw-cli-codecollection#162]
**Scope**
A basic SLI codebundle specific to Jenkins X that does a number of checks and computes a health score between 0 and 1.

**Requested By (Optional)**
- Ask Kyle for customer name

**Related Integrations**
eg:
- Kubernetes (?)

**Definition of Done**
- [ ] Codebundle Implementation accomplishes scope (or provide a justification for why it may differ)
- [ ] Attach a screenshot of the codebundle pushing a metric locally (if an SLI) or showing a report (if a taskset)
- [ ] Attach a screenshot of the SLI or Taskset running in a workspace.

**Optional Comments**

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
