### ISSUE TITLE
[Codebundle] JenkinsX Troubleshooting

### ISSUE THREAD

**Issue by jon-funk** [runwhen-contrib/rw-cli-codecollection#191]
**Scope**
- Taskset for troubleshooting JenkinsX 

**Requested By (Optional)**
- RunWhen

**Related Integrations**
- JenkinsX
- Kubernetes

**Definition of Done**
- [x] Codebundle Implementation accomplishes scope (or provide a justification for why it may differ)
- [x] Attach a screenshot of the codebundle pushing a metric locally (if an SLI) or showing a report (if a taskset)
- [x] Attach a screenshot of the SLI or Taskset running in a workspace.

**Optional Comments**
- from author: working on EKS cluster

**Comment by harsh098** [comment]
# Codebundle
Repository :- [https://github.com/harsh098/jenkins-x-codecollection](https://github.com/harsh098/jenkins-x-codecollection)

## SLIs Running
![Screenshot from 2023-10-25 02-57-01](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/23445112/bd95e387-d916-433e-ab8e-be76b1e52362)

## Tasksets Running
![Screenshot from 2023-10-27 12-13-42](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/23445112/4fb9909c-f720-45a0-902b-62b485f6c47e)  

![Screenshot from 2023-10-27 12-13-57](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/23445112/2bf6fba1-738f-4751-ab15-fe11c92d9138)  

![Screenshot from 2023-10-27 12-14-06](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/23445112/91fdfffa-5540-46d5-ba1b-b0ac7cde1857)

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
