### ISSUE TITLE
Next steps string on unhealthy ingress objects found is not as specific as details string

### ISSUE THREAD

**Issue by more-dinner** [runwhen-contrib/rw-cli-codecollection#196]
From -
https://app.beta.runwhen.com/map/b-sandbox#selectedRunSessions=24

## Expected Behavior
Next steps should say something like "check namespace online-boutique for manifests referring to service name my-app-frontend" or "In namespace online-boutique, my-app-frontend does not exist.  Check manifests."  Instead, it says "Check namespace online-boutique for service name my-app-frontend."  I'm not sure if that next steps means that I should check for health, existence, performance, capacity, etc., when it is clear from the details string that the issue is that the service simply doesn't exist.

## Current Behavior
Next steps:
```
Check namespace online-boutique for service name my-app-frontend.
Check namespace online-boutique for service name my-app2-frontend.
```
Issue string:
Details:
```
Details

The following unhealthy objects were found:

Ingress: my-app
Backend Service: my-app-frontend, Port: 80
Error: Service my-app-frontend does not exist
Next Step: Check namespace online-boutique for service name my-app-frontend.
Health Status: Unhealthy
------------
Ingress: my-app2
Backend Service: my-app2-frontend, Port: 80
Error: Service my-app2-frontend does not exist
Next Step: Check namespace online-boutique for service name my-app2-frontend.
Health Status: Unhealthy
------------
```

## Possible Solution
See above re: a more helpful next steps string suggestions

## Steps to Reproduce
https://app.beta.runwhen.com/map/b-sandbox#selectedRunSessions=24

**Comment by jon-funk** [comment]
closing - outdated after nextsteps reworking
