### ISSUE TITLE
[Codebundle] Postgres Blocked Query and Blocked Backends Inspection

### ISSUE THREAD

**Issue by harsh098** [runwhen-contrib/rw-cli-codecollection#240]
**Scope**
Runs a taskset inspection on a postgresql database, checking for blocked queries  and table locks on Postgres and Report Remediations.

**Requested By (Optional)**  
- @harsh098 

**Related Integrations**  
- Kubernetes
- Postgresql

**Definition of Done**  
 - [ ] Attach a screenshot of the SLI or Taskset running in a workspace.  
 - [ ] Codebundle Implementation accomplishes scope (or provide a justification for why it may differ)

 - [ ] Attach a screenshot of the codebundle pushing a metric locally (if an SLI) or showing a report (if a taskset)

**Optional Comments**  
This could potentially be split into 2 variants: one for public but authenticated db instances, and one for kubernetes workloads connected to via the kube api

**Comment by harsh098** [comment]
# Codebundle Repo
[https://github.com/harsh098/postgres-codecollection](https://github.com/harsh098/postgres-codecollection)

# Screenshots

 ## Taskset
Checks for Blocked Queries on the Cluster  



![Image](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/23445112/69febb15-ad8b-4c16-9f82-f5f3375812a5)


### Bonus : Added Mitigations

![Image](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/23445112/60c43627-70ae-4147-9387-945fa81a242d)



## SLI
Reports no of blcoking queries on the Postgres Cluster



![Image](https://github.com/runwhen-contrib/rw-cli-codecollection/assets/23445112/5979f74f-9b8d-46a3-bd80-26e947944b01)

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
