### ISSUE TITLE
[Codebundle] ArgoCD Infra Triage

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/rw-cli-codecollection#7]
Troubleshoot / triage argocd controller resources: 

- [ ] core tasks created
- [ ] tag/docstring created
- [ ] command-list additions/flags
- [ ] raiseissue added

**Comment by stewartshea** [comment]
Argocdc multi-cluster taskset ideas: 
- HA configuration checks (Redis, multiple instances/autoscaling components, metrics export for SLI)- read the helm chart?
- Remote/Managed cluster management / registration health (label validation argocd.argoproj.io/secret-type: cluster)
- Sync and work queue metrics (similar to flux metrics) - pull this from their prom/grafana stock deployment 
- e.g. 10,000 apps = 35 minutes of sync time 
- Check or restrict the default project 
- Check sync configuration / webhook --> some people deisable sync and solely rely on webhook, but these could be missed.   
- ArgoCD Config Management plugin?

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
