### ISSUE TITLE
[Codebundle] Check PDB Configuration

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/rw-cli-codecollection#8]
Check PDB configurations and provide recommendations. Make this more helpful than Googles alerts about missing pdbs that appear to lack any direct resolution. 

- [ ] core tasks created
- [ ] tag/docstring created
- [ ] command-list additions/flags
- [ ] raiseissue added

**Comment by harsh098** [comment]
please assign this issue to me @stewartshea and @jon-funk .

**Comment by jon-funk** [comment]
With the current PDB task this issue is looking a bit outdated.

Current task that tackles PDBs:
https://github.com/runwhen-contrib/rw-cli-codecollection/blob/main/codebundles/k8s-namespace-healthcheck/runbook.robot#L471

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
