### ISSUE TITLE
[Codebundle] Kube-prometheus-stack triage

### ISSUE THREAD

**Issue by stewartshea** [runwhen-contrib/rw-cli-codecollection#9]
https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

Create triage tasks for each of the components in the stack above. 

- [ ] core tasks created
- [ ] tag/docstring created
- [ ] command-list additions/flags
- [ ] raiseissue added

**Comment by jon-funk** [comment]
This codebundle request and detail history is being migrated to an internal tracking tool for authors. Please reach out to the RunWhen team if you have any questions.
